# NumPy

In [1]:
#import numpy library
import numpy as np

In [4]:
#create simple array from the list

arr = np.array([[5,6,7,8],[9,10,11,12]])
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.ndim # dimantion

2

In [6]:
arr.shape # shape of array

(2, 4)

In [7]:
type(arr)

numpy.ndarray

In [10]:
arr.data #memory location

# Random Number Generater

In [13]:
#import numpy library
import numpy as np

from numpy import random

In [16]:
x= random.randint(100)
x

20

In [17]:
x= random.rand(100)
x

array([0.83800928, 0.32405091, 0.96738851, 0.29921317, 0.98018273,
       0.08752663, 0.54286262, 0.37922564, 0.0299454 , 0.09092801,
       0.84417093, 0.04461391, 0.43559553, 0.24925226, 0.42128305,
       0.43935518, 0.97760497, 0.87075727, 0.42755555, 0.74869614,
       0.24779832, 0.15456909, 0.17724988, 0.66908815, 0.91323116,
       0.61217372, 0.53129693, 0.43895711, 0.88972053, 0.55949687,
       0.93456209, 0.93552481, 0.51590786, 0.53045493, 0.49057862,
       0.6132481 , 0.37624321, 0.59522209, 0.16871694, 0.55865602,
       0.87047521, 0.95093732, 0.36880806, 0.72840012, 0.42463291,
       0.24485351, 0.12145341, 0.7266734 , 0.9320377 , 0.45441669,
       0.75697111, 0.3470346 , 0.94959663, 0.58950494, 0.89211256,
       0.95712676, 0.76037429, 0.51909276, 0.62557649, 0.33566238,
       0.25239877, 0.42034288, 0.80554421, 0.63965873, 0.18393907,
       0.33264446, 0.10991535, 0.63628373, 0.69495691, 0.6038257 ,
       0.02103549, 0.85977562, 0.87841949, 0.74226995, 0.96719

In [18]:
x= random.randint(100, size=(5))
x

array([89, 33,  6, 99, 10])

In [19]:
x= random.randint(100, size=(5,3))
x

array([[57, 81, 87],
       [15, 87, 31],
       [99, 43, 18],
       [35, 97, 10],
       [ 7, 46, 41]])

In [20]:
#a=1D arry,with 7 integer
#b=1D arry,with 7 integer
#math operation.

In [23]:
x= random.randint(100, size=(7))
y= random.randint(50, size=(7))
x

array([32, 74,  0, 77, 55, 31, 66])

In [25]:
y

array([22, 40, 38, 45, 10, 24, 21])

In [26]:
x+y

array([ 54, 114,  38, 122,  65,  55,  87])

In [27]:
x/y

array([1.45454545, 1.85      , 0.        , 1.71111111, 5.5       ,
       1.29166667, 3.14285714])

In [28]:
x**x

array([          0,           0,           1,   827793981,  2006722247,
       -2010103841,           0], dtype=int32)

In [29]:
x-y

array([ 10,  34, -38,  32,  45,   7,  45])

# Matrix in NumPy

In [31]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [33]:
a=np.matrix('1 2 3; 4 5 6; 7 8 9')
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
b=np.matrix([[1,2,3],[7,8,9]])
b

matrix([[1, 2, 3],
        [7, 8, 9]])

# Measure of Central Tendency

In [37]:
arr = np.array([[5,6,7],[9,10,11],[8,4,3]])
arr

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [ 8,  4,  3]])

In [38]:
np.amin(arr)

3

In [39]:
np.amax(arr)

11

In [40]:
np.mean(arr)

7.0

In [41]:
np.median(arr)

7.0

In [43]:
np.std(arr) #standard deviation

2.581988897471611

In [44]:
np.var(arr)

6.666666666666667